
name: Render video Ma
on:
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: create env file ${{ secrets.API }}
        run: |
          ${{ secrets.API }}
          touch .env
      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
