
name: Render video Ma
on:
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: create env file
        with: # Set the secret as an input
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        env: # Or as an environment variable
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
